import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Default user ID - since we're not using authentication
const DEFAULT_USER_ID = '00000000-0000-0000-0000-000000000001';

// Seed categories
const categories = [
  'Main Course',
  'Salad',
  'Soup',
  'Dessert',
  'Snack',
  'Breakfast',
  'Beverage',
];

// Seed tags
const tags = [
  'breakfast',
  'lunch',
  'dinner',
  'vegetarian',
  'vegan',
  'quick',
  'low-carb',
  'high-protein',
  'gluten-free',
  'dairy-free',
  'healthy',
  'comfort-food',
];

// Sample recipes data
const recipes = [
  {
    title: 'Greek Salad with Feta',
    description: 'A refreshing Mediterranean salad with crisp vegetables and tangy feta cheese.',
    ingredients: [
      { name: 'Tomatoes', quantity: 2, unit: 'pieces', note: 'diced' },
      { name: 'Cucumber', quantity: 1, unit: 'piece', note: 'sliced' },
      { name: 'Red onion', quantity: 0.5, unit: 'piece', note: 'thinly sliced' },
      { name: 'Black olives', quantity: 50, unit: 'g' },
      { name: 'Feta cheese', quantity: 100, unit: 'g', note: 'crumbled' },
      { name: 'Olive oil', quantity: 30, unit: 'ml' },
      { name: 'Lemon juice', quantity: 15, unit: 'ml' },
      { name: 'Oregano', quantity: 5, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Wash and chop all vegetables',
      'Combine tomatoes, cucumber, red onion in a large bowl',
      'Add black olives and crumbled feta cheese',
      'Drizzle with olive oil and lemon juice',
      'Season with oregano and salt',
      'Toss gently and serve',
    ],
    tags: ['lunch', 'dinner', 'vegetarian', 'healthy', 'quick'],
    category: 'Salad',
    servings: 2,
    cookTimeMin: 10,
    kcalPerServing: 280,
    proteinPerServing: 12.5,
    fatPerServing: 22.0,
    carbsPerServing: 8.5,
  },
  {
    title: 'Grilled Chicken Breast with Vegetables',
    description: 'Lean protein with roasted seasonal vegetables.',
    ingredients: [
      { name: 'Chicken breast', quantity: 200, unit: 'g' },
      { name: 'Bell pepper', quantity: 1, unit: 'piece', note: 'sliced' },
      { name: 'Zucchini', quantity: 1, unit: 'piece', note: 'sliced' },
      { name: 'Broccoli', quantity: 150, unit: 'g' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', note: 'minced' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Preheat grill or pan to medium-high heat',
      'Season chicken breast with salt and pepper',
      'Grill chicken for 6-7 minutes per side until cooked through',
      'Heat olive oil in a pan, add garlic',
      'Add vegetables and cook for 8-10 minutes until tender',
      'Serve chicken with roasted vegetables',
    ],
    tags: ['lunch', 'dinner', 'high-protein', 'healthy', 'low-carb'],
    category: 'Main Course',
    servings: 1,
    cookTimeMin: 25,
    kcalPerServing: 420,
    proteinPerServing: 48.0,
    fatPerServing: 15.0,
    carbsPerServing: 12.0,
  },
  {
    title: 'Overnight Oats with Berries',
    description: 'Creamy overnight oats topped with fresh mixed berries.',
    ingredients: [
      { name: 'Rolled oats', quantity: 60, unit: 'g' },
      { name: 'Greek yogurt', quantity: 100, unit: 'g' },
      { name: 'Almond milk', quantity: 100, unit: 'ml' },
      { name: 'Chia seeds', quantity: 15, unit: 'g' },
      { name: 'Honey', quantity: 20, unit: 'g' },
      { name: 'Mixed berries', quantity: 100, unit: 'g' },
      { name: 'Almonds', quantity: 15, unit: 'g', note: 'sliced' },
    ],
    steps: [
      'Combine oats, yogurt, almond milk, and chia seeds in a jar',
      'Stir in honey',
      'Cover and refrigerate overnight',
      'In the morning, top with fresh berries and almonds',
      'Serve cold',
    ],
    tags: ['breakfast', 'vegetarian', 'healthy', 'quick'],
    category: 'Breakfast',
    servings: 1,
    cookTimeMin: 5,
    kcalPerServing: 385,
    proteinPerServing: 18.5,
    fatPerServing: 12.5,
    carbsPerServing: 52.0,
  },
  {
    title: 'Vegetable Stir Fry',
    description: 'Colorful vegetables stir-fried in a savory sauce.',
    ingredients: [
      { name: 'Bell peppers', quantity: 2, unit: 'pieces', note: 'sliced' },
      { name: 'Carrots', quantity: 2, unit: 'pieces', note: 'julienned' },
      { name: 'Snow peas', quantity: 150, unit: 'g' },
      { name: 'Mushrooms', quantity: 150, unit: 'g', note: 'sliced' },
      { name: 'Soy sauce', quantity: 30, unit: 'ml' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Ginger', quantity: 10, unit: 'g', note: 'minced' },
      { name: 'Vegetable oil', quantity: 20, unit: 'ml' },
      { name: 'Sesame oil', quantity: 5, unit: 'ml' },
    ],
    steps: [
      'Heat vegetable oil in a large wok or pan over high heat',
      'Add garlic and ginger, stir-fry for 30 seconds',
      'Add carrots and stir-fry for 2 minutes',
      'Add bell peppers and snow peas, cook for 3 minutes',
      'Add mushrooms and cook for another 2 minutes',
      'Add soy sauce and sesame oil, toss to combine',
      'Serve immediately',
    ],
    tags: ['lunch', 'dinner', 'vegetarian', 'vegan', 'healthy', 'quick'],
    category: 'Main Course',
    servings: 2,
    cookTimeMin: 15,
    kcalPerServing: 180,
    proteinPerServing: 8.5,
    fatPerServing: 8.0,
    carbsPerServing: 18.0,
  },
  {
    title: 'Salmon with Quinoa and Asparagus',
    description: 'Omega-3 rich salmon with whole grain quinoa and green asparagus.',
    ingredients: [
      { name: 'Salmon fillet', quantity: 150, unit: 'g' },
      { name: 'Quinoa', quantity: 80, unit: 'g', note: 'dry' },
      { name: 'Asparagus', quantity: 200, unit: 'g' },
      { name: 'Lemon', quantity: 1, unit: 'piece', note: 'juiced' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Dill', quantity: 5, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Rinse quinoa and cook according to package instructions',
      'Preheat oven to 200°C',
      'Season salmon with salt, pepper, and lemon juice',
      'Bake salmon for 12-15 minutes',
      'Steam asparagus for 5-6 minutes until tender',
      'Fluff quinoa with fork and add olive oil and dill',
      'Serve salmon over quinoa with asparagus on the side',
    ],
    tags: ['lunch', 'dinner', 'high-protein', 'healthy'],
    category: 'Main Course',
    servings: 1,
    cookTimeMin: 30,
    kcalPerServing: 565,
    proteinPerServing: 42.0,
    fatPerServing: 22.5,
    carbsPerServing: 52.0,
  },
  {
    title: 'Avocado Toast',
    description: 'Simple and nutritious toast topped with mashed avocado.',
    ingredients: [
      { name: 'Whole grain bread', quantity: 2, unit: 'slices' },
      { name: 'Avocado', quantity: 1, unit: 'piece', note: 'ripe' },
      { name: 'Cherry tomatoes', quantity: 5, unit: 'pieces', note: 'halved' },
      { name: 'Red pepper flakes', quantity: 2, unit: 'g' },
      { name: 'Lemon juice', quantity: 5, unit: 'ml' },
      { name: 'Salt', quantity: 1, unit: 'g' },
    ],
    steps: [
      'Toast the bread until golden brown',
      'Cut avocado in half, remove pit, and scoop out flesh',
      'Mash avocado with fork and mix with lemon juice and salt',
      'Spread avocado mixture on toast',
      'Top with cherry tomatoes',
      'Sprinkle with red pepper flakes',
    ],
    tags: ['breakfast', 'lunch', 'vegetarian', 'vegan', 'quick'],
    category: 'Breakfast',
    servings: 1,
    cookTimeMin: 5,
    kcalPerServing: 320,
    proteinPerServing: 10.5,
    fatPerServing: 22.0,
    carbsPerServing: 28.0,
  },
  {
    title: 'Tomato Basil Soup',
    description: 'Creamy and comforting tomato soup with fresh basil.',
    ingredients: [
      { name: 'Tomatoes', quantity: 800, unit: 'g', note: 'canned' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Vegetable broth', quantity: 400, unit: 'ml' },
      { name: 'Heavy cream', quantity: 100, unit: 'ml' },
      { name: 'Fresh basil', quantity: 20, unit: 'g' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Heat olive oil in a large pot over medium heat',
      'Add onion and garlic, cook until softened',
      'Add canned tomatoes and vegetable broth',
      'Simmer for 20 minutes',
      'Use immersion blender to puree soup',
      'Stir in heavy cream and fresh basil',
      'Season with salt and pepper to taste',
    ],
    tags: ['lunch', 'dinner', 'vegetarian', 'comfort-food'],
    category: 'Soup',
    servings: 4,
    cookTimeMin: 30,
    kcalPerServing: 185,
    proteinPerServing: 4.5,
    fatPerServing: 12.0,
    carbsPerServing: 16.5,
  },
  {
    title: 'Greek Yogurt with Honey and Walnuts',
    description: 'High-protein breakfast with natural sweetness.',
    ingredients: [
      { name: 'Greek yogurt', quantity: 200, unit: 'g' },
      { name: 'Honey', quantity: 30, unit: 'g' },
      { name: 'Walnuts', quantity: 30, unit: 'g', note: 'chopped' },
      { name: 'Blueberries', quantity: 80, unit: 'g' },
    ],
    steps: [
      'Scoop Greek yogurt into a bowl',
      'Drizzle with honey',
      'Top with chopped walnuts and blueberries',
      'Serve immediately',
    ],
    tags: ['breakfast', 'vegetarian', 'high-protein', 'quick'],
    category: 'Breakfast',
    servings: 1,
    cookTimeMin: 2,
    kcalPerServing: 285,
    proteinPerServing: 20.0,
    fatPerServing: 10.5,
    carbsPerServing: 32.0,
  },
  {
    title: 'Chicken Caesar Salad',
    description: 'Classic Caesar salad with grilled chicken.',
    ingredients: [
      { name: 'Romaine lettuce', quantity: 150, unit: 'g', note: 'chopped' },
      { name: 'Chicken breast', quantity: 150, unit: 'g', note: 'grilled' },
      { name: 'Caesar dressing', quantity: 40, unit: 'ml' },
      { name: 'Parmesan cheese', quantity: 30, unit: 'g', note: 'grated' },
      { name: 'Croutons', quantity: 30, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Grill chicken breast and slice',
      'Combine lettuce, chicken, and croutons in a bowl',
      'Toss with Caesar dressing',
      'Top with grated Parmesan cheese',
      'Season with black pepper',
    ],
    tags: ['lunch', 'dinner', 'high-protein', 'quick'],
    category: 'Salad',
    servings: 1,
    cookTimeMin: 15,
    kcalPerServing: 485,
    proteinPerServing: 45.0,
    fatPerServing: 22.0,
    carbsPerServing: 24.0,
  },
  {
    title: 'Chocolate Chip Cookies',
    description: 'Classic homemade chocolate chip cookies.',
    ingredients: [
      { name: 'All-purpose flour', quantity: 200, unit: 'g' },
      { name: 'Butter', quantity: 100, unit: 'g', note: 'softened' },
      { name: 'Brown sugar', quantity: 80, unit: 'g' },
      { name: 'White sugar', quantity: 50, unit: 'g' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Chocolate chips', quantity: 150, unit: 'g' },
      { name: 'Vanilla extract', quantity: 5, unit: 'ml' },
      { name: 'Baking soda', quantity: 3, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Preheat oven to 175°C',
      'Cream butter and sugars until light and fluffy',
      'Beat in egg and vanilla extract',
      'Mix flour, baking soda, and salt in separate bowl',
      'Gradually combine wet and dry ingredients',
      'Fold in chocolate chips',
      'Drop rounded tablespoons onto baking sheet',
      'Bake for 10-12 minutes until golden',
    ],
    tags: ['dessert', 'snack', 'vegetarian', 'comfort-food'],
    category: 'Dessert',
    servings: 12,
    cookTimeMin: 30,
    kcalPerServing: 210,
    proteinPerServing: 2.5,
    fatPerServing: 10.0,
    carbsPerServing: 28.0,
  },
  {
    title: 'Tuna Pasta Salad',
    description: 'Hearty pasta salad with flaked tuna and vegetables.',
    ingredients: [
      { name: 'Pasta', quantity: 150, unit: 'g', note: 'dry' },
      { name: 'Tuna', quantity: 100, unit: 'g', note: 'canned, drained' },
      { name: 'Cherry tomatoes', quantity: 100, unit: 'g', note: 'halved' },
      { name: 'Cucumber', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Red onion', quantity: 0.25, unit: 'piece', note: 'diced' },
      { name: 'Mayonnaise', quantity: 40, unit: 'ml' },
      { name: 'Lemon juice', quantity: 10, unit: 'ml' },
      { name: 'Dill', quantity: 5, unit: 'g', note: 'chopped' },
      { name: 'Salt', quantity: 2, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Cook pasta according to package instructions, cool',
      'Drain tuna and flake with fork',
      'Combine cooked pasta with tuna and vegetables',
      'Mix mayonnaise, lemon juice, and dill for dressing',
      'Toss salad with dressing',
      'Season with salt and pepper',
    ],
    tags: ['lunch', 'high-protein', 'quick'],
    category: 'Main Course',
    servings: 2,
    cookTimeMin: 20,
    kcalPerServing: 385,
    proteinPerServing: 28.0,
    fatPerServing: 12.5,
    carbsPerServing: 42.0,
  },
  {
    title: 'Beef Stir Fry with Rice',
    description: 'Tender beef strips in savory sauce over steamed rice.',
    ingredients: [
      { name: 'Beef sirloin', quantity: 200, unit: 'g', note: 'thinly sliced' },
      { name: 'Rice', quantity: 100, unit: 'g', note: 'dry' },
      { name: 'Broccoli', quantity: 200, unit: 'g' },
      { name: 'Carrots', quantity: 1, unit: 'piece', note: 'julienned' },
      { name: 'Soy sauce', quantity: 40, unit: 'ml' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Ginger', quantity: 10, unit: 'g', note: 'minced' },
      { name: 'Vegetable oil', quantity: 25, unit: 'ml' },
      { name: 'Cornstarch', quantity: 5, unit: 'g' },
    ],
    steps: [
      'Cook rice according to package instructions',
      'Slice beef thinly and coat with cornstarch',
      'Heat oil in wok over high heat',
      'Stir-fry beef for 2-3 minutes, remove from pan',
      'Add garlic, ginger, and vegetables',
      'Cook vegetables for 3-4 minutes',
      'Return beef to pan, add soy sauce',
      'Stir-fry for 1 minute, serve over rice',
    ],
    tags: ['dinner', 'high-protein'],
    category: 'Main Course',
    servings: 2,
    cookTimeMin: 30,
    kcalPerServing: 550,
    proteinPerServing: 38.0,
    fatPerServing: 18.5,
    carbsPerServing: 58.0,
  },
  {
    title: 'Green Smoothie Bowl',
    description: 'Nutrient-packed smoothie bowl topped with fruits and seeds.',
    ingredients: [
      { name: 'Spinach', quantity: 80, unit: 'g' },
      { name: 'Banana', quantity: 1, unit: 'piece', note: 'frozen' },
      { name: 'Mango', quantity: 100, unit: 'g', note: 'frozen' },
      { name: 'Greek yogurt', quantity: 100, unit: 'g' },
      { name: 'Almond milk', quantity: 100, unit: 'ml' },
      { name: 'Chia seeds', quantity: 10, unit: 'g' },
      { name: 'Granola', quantity: 30, unit: 'g' },
      { name: 'Blueberries', quantity: 50, unit: 'g' },
    ],
    steps: [
      'Blend spinach, banana, mango, yogurt, and almond milk until smooth',
      'Pour into bowl',
      'Top with chia seeds, granola, and blueberries',
      'Serve immediately',
    ],
    tags: ['breakfast', 'vegetarian', 'healthy', 'quick'],
    category: 'Breakfast',
    servings: 1,
    cookTimeMin: 5,
    kcalPerServing: 365,
    proteinPerServing: 18.0,
    fatPerServing: 8.5,
    carbsPerServing: 62.0,
  },
  {
    title: 'Quinoa Stuffed Bell Peppers',
    description: 'Colorful bell peppers filled with quinoa and vegetables.',
    ingredients: [
      { name: 'Bell peppers', quantity: 4, unit: 'pieces', note: 'halved' },
      { name: 'Quinoa', quantity: 150, unit: 'g', note: 'dry' },
      { name: 'Black beans', quantity: 200, unit: 'g', note: 'canned' },
      { name: 'Corn', quantity: 150, unit: 'g' },
      { name: 'Tomatoes', quantity: 200, unit: 'g', note: 'diced' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Cumin', quantity: 5, unit: 'g' },
      { name: 'Paprika', quantity: 5, unit: 'g' },
      { name: 'Salt', quantity: 3, unit: 'g' },
    ],
    steps: [
      'Preheat oven to 190°C',
      'Cook quinoa according to package instructions',
      'Sauté onion and garlic in olive oil',
      'Add black beans, corn, tomatoes, and spices',
      'Combine with cooked quinoa',
      'Stuff bell peppers with quinoa mixture',
      'Bake for 25-30 minutes until peppers are tender',
    ],
    tags: ['lunch', 'dinner', 'vegetarian', 'vegan', 'healthy'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 45,
    kcalPerServing: 285,
    proteinPerServing: 12.5,
    fatPerServing: 7.0,
    carbsPerServing: 48.0,
  },
  {
    title: 'Egg Scramble with Vegetables',
    description: 'Protein-rich scrambled eggs with sautéed vegetables.',
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'pieces' },
      { name: 'Spinach', quantity: 100, unit: 'g' },
      { name: 'Mushrooms', quantity: 100, unit: 'g', note: 'sliced' },
      { name: 'Cherry tomatoes', quantity: 8, unit: 'pieces', note: 'halved' },
      { name: 'Onion', quantity: 0.5, unit: 'piece', note: 'diced' },
      { name: 'Olive oil', quantity: 10, unit: 'ml' },
      { name: 'Salt', quantity: 2, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Heat olive oil in a non-stick pan',
      'Sauté onion and mushrooms for 3-4 minutes',
      'Add spinach and cook until wilted',
      'Beat eggs in a bowl and season with salt and pepper',
      'Pour eggs into pan with vegetables',
      'Scramble gently until cooked to desired consistency',
      'Add cherry tomatoes and serve',
    ],
    tags: ['breakfast', 'high-protein', 'quick'],
    category: 'Breakfast',
    servings: 1,
    cookTimeMin: 10,
    kcalPerServing: 320,
    proteinPerServing: 22.5,
    fatPerServing: 18.0,
    carbsPerServing: 12.0,
  },
  {
    title: 'Chicken Curry with Rice',
    description: 'Aromatic chicken curry with basmati rice.',
    ingredients: [
      { name: 'Chicken thighs', quantity: 300, unit: 'g' },
      { name: 'Rice', quantity: 150, unit: 'g', note: 'dry' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Garlic', quantity: 4, unit: 'cloves', note: 'minced' },
      { name: 'Ginger', quantity: 20, unit: 'g', note: 'minced' },
      { name: 'Curry powder', quantity: 10, unit: 'g' },
      { name: 'Coconut milk', quantity: 200, unit: 'ml' },
      { name: 'Tomato paste', quantity: 30, unit: 'g' },
      { name: 'Vegetable oil', quantity: 20, unit: 'ml' },
      { name: 'Salt', quantity: 3, unit: 'g' },
    ],
    steps: [
      'Cook rice according to package instructions',
      'Heat oil in a large pot, add onion and cook until soft',
      'Add garlic and ginger, cook for 1 minute',
      'Add chicken and cook until browned',
      'Stir in curry powder and tomato paste',
      'Pour in coconut milk and simmer for 20 minutes',
      'Season with salt to taste',
      'Serve over basmati rice',
    ],
    tags: ['dinner', 'high-protein', 'comfort-food'],
    category: 'Main Course',
    servings: 3,
    cookTimeMin: 40,
    kcalPerServing: 485,
    proteinPerServing: 35.0,
    fatPerServing: 22.5,
    carbsPerServing: 48.0,
  },
  {
    title: 'Chickpea Salad',
    description: 'Protein-packed chickpea salad with fresh vegetables.',
    ingredients: [
      { name: 'Chickpeas', quantity: 400, unit: 'g', note: 'canned, drained' },
      { name: 'Cucumber', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Cherry tomatoes', quantity: 150, unit: 'g', note: 'halved' },
      { name: 'Red onion', quantity: 0.5, unit: 'piece', note: 'diced' },
      { name: 'Parsley', quantity: 20, unit: 'g', note: 'chopped' },
      { name: 'Lemon juice', quantity: 30, unit: 'ml' },
      { name: 'Olive oil', quantity: 30, unit: 'ml' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', note: 'minced' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Drain and rinse chickpeas',
      'Combine chickpeas with vegetables and parsley',
      'Whisk lemon juice, olive oil, garlic, cumin, and salt',
      'Pour dressing over salad and toss',
      'Let marinate for at least 30 minutes',
    ],
    tags: ['lunch', 'vegetarian', 'vegan', 'high-protein', 'healthy'],
    category: 'Salad',
    servings: 3,
    cookTimeMin: 15,
    kcalPerServing: 245,
    proteinPerServing: 12.0,
    fatPerServing: 10.5,
    carbsPerServing: 32.0,
  },
  {
    title: 'Baked Turkey Meatballs',
    description: 'Lean turkey meatballs baked with herbs and served with marinara.',
    ingredients: [
      { name: 'Ground turkey', quantity: 500, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 60, unit: 'g' },
      { name: 'Parmesan cheese', quantity: 30, unit: 'g', note: 'grated' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', note: 'minced' },
      { name: 'Onion', quantity: 0.5, unit: 'piece', note: 'finely chopped' },
      { name: 'Olive oil', quantity: 15, unit: 'ml' },
      { name: 'Marinara sauce', quantity: 250, unit: 'ml' },
      { name: 'Italian seasoning', quantity: 5, unit: 'g' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Preheat oven to 200°C and line a baking sheet with parchment.',
      'Combine turkey, breadcrumbs, parmesan, egg, garlic, onion, seasoning, salt, and pepper.',
      'Form mixture into meatballs and place on baking sheet.',
      'Brush lightly with olive oil and bake for 18-20 minutes.',
      'Warm marinara sauce and serve meatballs with sauce.',
    ],
    tags: ['dinner', 'high-protein', 'comfort-food'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 30,
    kcalPerServing: 320,
    proteinPerServing: 32.0,
    fatPerServing: 14.0,
    carbsPerServing: 20.0,
  },
  {
    title: 'Vegetarian Stuffed Mushrooms',
    description: 'Portobello mushrooms filled with spinach, feta, and quinoa.',
    ingredients: [
      { name: 'Portobello mushrooms', quantity: 6, unit: 'pieces', note: 'stems removed' },
      { name: 'Quinoa', quantity: 100, unit: 'g', note: 'cooked' },
      { name: 'Spinach', quantity: 120, unit: 'g', note: 'chopped' },
      { name: 'Feta cheese', quantity: 80, unit: 'g', note: 'crumbled' },
      { name: 'Sun-dried tomatoes', quantity: 40, unit: 'g', note: 'chopped' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', note: 'minced' },
      { name: 'Salt', quantity: 2, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Preheat oven to 190°C.',
      'Brush mushrooms with olive oil and place on a baking sheet gill side up.',
      'Sauté spinach with garlic until wilted.',
      'Combine cooked quinoa, spinach, feta, and sun-dried tomatoes. Season with salt and pepper.',
      'Fill mushrooms with mixture and bake for 15 minutes.',
    ],
    tags: ['appetizer', 'vegetarian', 'healthy'],
    category: 'Appetizer',
    servings: 3,
    cookTimeMin: 25,
    kcalPerServing: 210,
    proteinPerServing: 11.5,
    fatPerServing: 12.0,
    carbsPerServing: 16.0,
  },
  {
    title: 'Lentil & Sweet Potato Stew',
    description: 'Hearty stew with red lentils and sweet potatoes in tomato broth.',
    ingredients: [
      { name: 'Red lentils', quantity: 180, unit: 'g' },
      { name: 'Sweet potato', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Carrot', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Celery', quantity: 2, unit: 'stalks', note: 'diced' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'chopped' },
      { name: 'Vegetable broth', quantity: 800, unit: 'ml' },
      { name: 'Tomato paste', quantity: 30, unit: 'g' },
      { name: 'Olive oil', quantity: 15, unit: 'ml' },
      { name: 'Cumin', quantity: 4, unit: 'g' },
      { name: 'Paprika', quantity: 3, unit: 'g' },
      { name: 'Bay leaf', quantity: 1, unit: 'piece' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Heat olive oil in a pot and sauté onion, carrot, and celery for 5 minutes.',
      'Add garlic, cumin, and paprika; cook 1 minute.',
      'Stir in tomato paste, lentils, sweet potato, broth, bay leaf, salt, and pepper.',
      'Bring to boil, reduce heat, and simmer 25 minutes until lentils are tender.',
      'Remove bay leaf and adjust seasoning.',
    ],
    tags: ['lunch', 'vegan', 'gluten-free', 'comfort-food'],
    category: 'Soup',
    servings: 4,
    cookTimeMin: 35,
    kcalPerServing: 265,
    proteinPerServing: 13.0,
    fatPerServing: 6.0,
    carbsPerServing: 44.0,
  },
  {
    title: 'Shrimp Fried Rice',
    description: 'Quick fried rice with shrimp, peas, carrots, and egg.',
    ingredients: [
      { name: 'Cooked rice', quantity: 400, unit: 'g', note: 'cooled' },
      { name: 'Shrimp', quantity: 250, unit: 'g', note: 'peeled' },
      { name: 'Eggs', quantity: 2, unit: 'pieces', note: 'beaten' },
      { name: 'Peas', quantity: 80, unit: 'g' },
      { name: 'Carrot', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Green onion', quantity: 2, unit: 'stalks', note: 'sliced' },
      { name: 'Soy sauce', quantity: 30, unit: 'ml' },
      { name: 'Sesame oil', quantity: 5, unit: 'ml' },
      { name: 'Vegetable oil', quantity: 20, unit: 'ml' },
      { name: 'Garlic', quantity: 2, unit: 'cloves', note: 'minced' },
      { name: 'Ginger', quantity: 5, unit: 'g', note: 'minced' },
    ],
    steps: [
      'Heat half the vegetable oil in a wok and scramble eggs; set aside.',
      'Add remaining oil, cook shrimp until pink, then set aside.',
      'Sauté carrot, peas, garlic, and ginger for 2 minutes.',
      'Add rice, soy sauce, and sesame oil; stir fry 3 minutes.',
      'Return shrimp and eggs, toss with green onion, and serve.',
    ],
    tags: ['dinner', 'quick', 'seafood'],
    category: 'Main Course',
    servings: 3,
    cookTimeMin: 20,
    kcalPerServing: 380,
    proteinPerServing: 24.0,
    fatPerServing: 12.0,
    carbsPerServing: 46.0,
  },
  {
    title: 'Greek Yogurt Chicken Salad',
    description: 'Light chicken salad dressed with Greek yogurt, herbs, and lemon.',
    ingredients: [
      { name: 'Cooked chicken breast', quantity: 320, unit: 'g', note: 'shredded' },
      { name: 'Greek yogurt', quantity: 120, unit: 'g' },
      { name: 'Celery', quantity: 2, unit: 'stalks', note: 'diced' },
      { name: 'Red grapes', quantity: 80, unit: 'g', note: 'halved' },
      { name: 'Almonds', quantity: 30, unit: 'g', note: 'sliced' },
      { name: 'Parsley', quantity: 10, unit: 'g', note: 'chopped' },
      { name: 'Lemon juice', quantity: 10, unit: 'ml' },
      { name: 'Dijon mustard', quantity: 10, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
      { name: 'Black pepper', quantity: 1, unit: 'g' },
    ],
    steps: [
      'In a bowl mix yogurt, lemon juice, mustard, salt, and pepper.',
      'Fold in shredded chicken, celery, grapes, almonds, and parsley.',
      'Chill for 15 minutes before serving on greens or bread.',
    ],
    tags: ['lunch', 'high-protein', 'gluten-free'],
    category: 'Salad',
    servings: 4,
    cookTimeMin: 15,
    kcalPerServing: 260,
    proteinPerServing: 26.0,
    fatPerServing: 11.0,
    carbsPerServing: 12.0,
  },
  {
    title: 'Pumpkin Oat Pancakes',
    description: 'Fluffy pancakes made with pumpkin puree and rolled oats.',
    ingredients: [
      { name: 'Rolled oats', quantity: 120, unit: 'g' },
      { name: 'Pumpkin puree', quantity: 150, unit: 'g' },
      { name: 'Almond milk', quantity: 180, unit: 'ml' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Maple syrup', quantity: 30, unit: 'ml' },
      { name: 'Baking powder', quantity: 6, unit: 'g' },
      { name: 'Cinnamon', quantity: 3, unit: 'g' },
      { name: 'Nutmeg', quantity: 1, unit: 'g' },
      { name: 'Salt', quantity: 1, unit: 'g' },
      { name: 'Coconut oil', quantity: 10, unit: 'ml', note: 'for cooking' },
    ],
    steps: [
      'Blend oats into flour using a blender.',
      'Add pumpkin, almond milk, egg, maple syrup, baking powder, cinnamon, nutmeg, and salt; blend until smooth.',
      'Heat coconut oil in a skillet over medium heat.',
      'Pour batter to form pancakes and cook 2-3 minutes per side.',
      'Serve warm with extra maple syrup if desired.',
    ],
    tags: ['breakfast', 'vegetarian', 'comfort-food'],
    category: 'Breakfast',
    servings: 3,
    cookTimeMin: 20,
    kcalPerServing: 290,
    proteinPerServing: 9.0,
    fatPerServing: 9.5,
    carbsPerServing: 42.0,
  },
  {
    title: 'Coconut Lime Salmon',
    description: 'Pan-seared salmon finished in a creamy coconut lime sauce.',
    ingredients: [
      { name: 'Salmon fillets', quantity: 4, unit: 'pieces', note: '120 g each' },
      { name: 'Coconut milk', quantity: 250, unit: 'ml' },
      { name: 'Lime', quantity: 1, unit: 'piece', note: 'zest and juice' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Ginger', quantity: 10, unit: 'g', note: 'grated' },
      { name: 'Fish sauce', quantity: 10, unit: 'ml' },
      { name: 'Sesame oil', quantity: 10, unit: 'ml' },
      { name: 'Chili flakes', quantity: 1, unit: 'g' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
      { name: 'Fresh cilantro', quantity: 10, unit: 'g', note: 'chopped' },
    ],
    steps: [
      'Season salmon with salt and pepper.',
      'Heat sesame oil in a skillet and sear salmon 3 minutes per side; remove.',
      'Sauté garlic and ginger 1 minute, then add coconut milk, lime zest, lime juice, fish sauce, and chili flakes.',
      'Simmer sauce 3 minutes, return salmon to skillet, cook 2 minutes.',
      'Garnish with cilantro before serving.',
    ],
    tags: ['dinner', 'seafood', 'gluten-free'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 25,
    kcalPerServing: 440,
    proteinPerServing: 32.0,
    fatPerServing: 30.0,
    carbsPerServing: 8.0,
  },
  {
    title: 'Pear Walnut Salad',
    description: 'Crisp romaine with sliced pears, toasted walnuts, and honey mustard dressing.',
    ingredients: [
      { name: 'Romaine lettuce', quantity: 200, unit: 'g', note: 'chopped' },
      { name: 'Pear', quantity: 2, unit: 'pieces', note: 'thinly sliced' },
      { name: 'Walnuts', quantity: 50, unit: 'g', note: 'toasted' },
      { name: 'Goat cheese', quantity: 60, unit: 'g', note: 'crumbled' },
      { name: 'Red onion', quantity: 0.25, unit: 'piece', note: 'thinly sliced' },
      { name: 'Olive oil', quantity: 30, unit: 'ml' },
      { name: 'Apple cider vinegar', quantity: 15, unit: 'ml' },
      { name: 'Honey', quantity: 15, unit: 'ml' },
      { name: 'Dijon mustard', quantity: 10, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
      { name: 'Black pepper', quantity: 1, unit: 'g' },
    ],
    steps: [
      'Whisk together olive oil, vinegar, honey, mustard, salt, and pepper.',
      'In a large bowl combine lettuce, pear slices, walnuts, goat cheese, and onion.',
      'Drizzle with dressing and toss gently.',
    ],
    tags: ['salad', 'vegetarian', 'quick'],
    category: 'Salad',
    servings: 4,
    cookTimeMin: 10,
    kcalPerServing: 250,
    proteinPerServing: 7.0,
    fatPerServing: 18.0,
    carbsPerServing: 18.0,
  },
  {
    title: 'Jackfruit BBQ Sandwich',
    description: 'Pulled jackfruit simmered in smoky barbecue sauce, served on whole-grain buns.',
    ingredients: [
      { name: 'Young jackfruit', quantity: 500, unit: 'g', note: 'canned in water, drained' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'sliced' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Tomato sauce', quantity: 240, unit: 'ml' },
      { name: 'Apple cider vinegar', quantity: 15, unit: 'ml' },
      { name: 'Maple syrup', quantity: 15, unit: 'ml' },
      { name: 'Smoked paprika', quantity: 5, unit: 'g' },
      { name: 'Chili powder', quantity: 4, unit: 'g' },
      { name: 'Whole-grain buns', quantity: 4, unit: 'pieces' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Heat olive oil in skillet and sauté onion until soft.',
      'Add garlic and jackfruit; cook 3 minutes.',
      'Stir in tomato sauce, vinegar, maple syrup, smoked paprika, chili powder, salt, and pepper.',
      'Simmer 15 minutes, shredding jackfruit with fork as it softens.',
      'Serve on toasted buns with favorite toppings.',
    ],
    tags: ['sandwich', 'vegan', 'comfort-food'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 30,
    kcalPerServing: 340,
    proteinPerServing: 8.0,
    fatPerServing: 9.0,
    carbsPerServing: 55.0,
  },
  {
    title: 'Thai Peanut Noodle Bowl',
    description: 'Rice noodles tossed in spicy peanut sauce with vegetables and tofu.',
    ingredients: [
      { name: 'Rice noodles', quantity: 250, unit: 'g' },
      { name: 'Firm tofu', quantity: 300, unit: 'g', note: 'cubed' },
      { name: 'Red bell pepper', quantity: 1, unit: 'piece', note: 'sliced' },
      { name: 'Carrot', quantity: 1, unit: 'piece', note: 'julienned' },
      { name: 'Snow peas', quantity: 120, unit: 'g' },
      { name: 'Peanut butter', quantity: 60, unit: 'g' },
      { name: 'Soy sauce', quantity: 30, unit: 'ml' },
      { name: 'Lime juice', quantity: 15, unit: 'ml' },
      { name: 'Honey', quantity: 15, unit: 'ml' },
      { name: 'Rice vinegar', quantity: 10, unit: 'ml' },
      { name: 'Sesame oil', quantity: 10, unit: 'ml' },
      { name: 'Chili paste', quantity: 5, unit: 'g' },
      { name: 'Peanuts', quantity: 30, unit: 'g', note: 'chopped' },
      { name: 'Fresh cilantro', quantity: 10, unit: 'g', note: 'chopped' },
    ],
    steps: [
      'Cook rice noodles according to package; drain.',
      'Whisk peanut butter, soy sauce, lime juice, honey, vinegar, sesame oil, and chili paste until smooth.',
      'Sauté tofu until golden, then add vegetables and cook 3 minutes.',
      'Combine noodles, tofu, vegetables, and sauce; toss well.',
      'Top with chopped peanuts and cilantro before serving.',
    ],
    tags: ['dinner', 'vegetarian', 'spicy'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 25,
    kcalPerServing: 420,
    proteinPerServing: 18.0,
    fatPerServing: 17.0,
    carbsPerServing: 51.0,
  },
  {
    title: 'Berry Chia Parfait',
    description: 'Layered chia seed pudding with mixed berries and granola.',
    ingredients: [
      { name: 'Chia seeds', quantity: 60, unit: 'g' },
      { name: 'Almond milk', quantity: 360, unit: 'ml' },
      { name: 'Vanilla extract', quantity: 5, unit: 'ml' },
      { name: 'Maple syrup', quantity: 20, unit: 'ml' },
      { name: 'Mixed berries', quantity: 200, unit: 'g' },
      { name: 'Granola', quantity: 80, unit: 'g' },
      { name: 'Greek yogurt', quantity: 150, unit: 'g' },
    ],
    steps: [
      'Combine chia seeds, almond milk, vanilla, and maple syrup; stir well.',
      'Refrigerate at least 2 hours or overnight until thickened.',
      'Layer chia pudding with Greek yogurt and berries in serving glasses.',
      'Top with granola and additional berries.',
    ],
    tags: ['breakfast', 'vegetarian', 'healthy'],
    category: 'Breakfast',
    servings: 4,
    cookTimeMin: 10,
    kcalPerServing: 260,
    proteinPerServing: 9.0,
    fatPerServing: 9.5,
    carbsPerServing: 34.0,
  },
  {
    title: 'Black Bean Quesadillas',
    description: 'Cheesy quesadillas filled with black beans, corn, and spices.',
    ingredients: [
      { name: 'Whole wheat tortillas', quantity: 4, unit: 'pieces' },
      { name: 'Black beans', quantity: 250, unit: 'g', note: 'canned, rinsed' },
      { name: 'Corn kernels', quantity: 120, unit: 'g' },
      { name: 'Cheddar cheese', quantity: 120, unit: 'g', note: 'shredded' },
      { name: 'Red onion', quantity: 0.25, unit: 'piece', note: 'diced' },
      { name: 'Cilantro', quantity: 10, unit: 'g', note: 'chopped' },
      { name: 'Lime juice', quantity: 10, unit: 'ml' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Chili powder', quantity: 3, unit: 'g' },
      { name: 'Olive oil', quantity: 15, unit: 'ml' },
    ],
    steps: [
      'Combine black beans, corn, onion, cilantro, lime juice, cumin, and chili powder.',
      'Spread mixture on half of each tortilla; top with cheese.',
      'Fold tortillas and cook in skillet with olive oil until golden on both sides.',
      'Cut into wedges and serve with salsa.',
    ],
    tags: ['lunch', 'vegetarian', 'comfort-food'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 20,
    kcalPerServing: 330,
    proteinPerServing: 15.0,
    fatPerServing: 12.0,
    carbsPerServing: 40.0,
  },
  {
    title: 'Mango Coconut Smoothie Bowl',
    description: 'Creamy smoothie bowl made with mango, banana, and coconut milk.',
    ingredients: [
      { name: 'Frozen mango', quantity: 200, unit: 'g' },
      { name: 'Frozen banana', quantity: 120, unit: 'g' },
      { name: 'Coconut milk', quantity: 180, unit: 'ml' },
      { name: 'Greek yogurt', quantity: 80, unit: 'g' },
      { name: 'Chia seeds', quantity: 15, unit: 'g' },
      { name: 'Coconut flakes', quantity: 20, unit: 'g' },
      { name: 'Fresh berries', quantity: 80, unit: 'g' },
      { name: 'Granola', quantity: 40, unit: 'g' },
    ],
    steps: [
      'Blend mango, banana, coconut milk, yogurt, and chia seeds until thick and smooth.',
      'Pour into bowls and top with coconut flakes, berries, and granola.',
    ],
    tags: ['breakfast', 'vegetarian', 'quick'],
    category: 'Breakfast',
    servings: 2,
    cookTimeMin: 5,
    kcalPerServing: 310,
    proteinPerServing: 11.0,
    fatPerServing: 12.0,
    carbsPerServing: 45.0,
  },
  {
    title: 'Herbed Couscous with Chickpeas',
    description: 'Fluffy couscous mixed with chickpeas, herbs, and lemon dressing.',
    ingredients: [
      { name: 'Couscous', quantity: 200, unit: 'g' },
      { name: 'Boiling water', quantity: 220, unit: 'ml' },
      { name: 'Chickpeas', quantity: 200, unit: 'g', note: 'canned, drained' },
      { name: 'Cherry tomatoes', quantity: 120, unit: 'g', note: 'halved' },
      { name: 'Cucumber', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Fresh parsley', quantity: 20, unit: 'g', note: 'chopped' },
      { name: 'Fresh mint', quantity: 10, unit: 'g', note: 'chopped' },
      { name: 'Lemon juice', quantity: 20, unit: 'ml' },
      { name: 'Olive oil', quantity: 25, unit: 'ml' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Place couscous in bowl, pour boiling water over, cover and let sit 5 minutes.',
      'Fluff couscous with fork and let cool slightly.',
      'Stir in chickpeas, tomatoes, cucumber, parsley, mint, lemon juice, olive oil, salt, and pepper.',
      'Serve warm or chilled.',
    ],
    tags: ['side', 'vegetarian', 'healthy'],
    category: 'Side Dish',
    servings: 4,
    cookTimeMin: 15,
    kcalPerServing: 240,
    proteinPerServing: 7.0,
    fatPerServing: 8.0,
    carbsPerServing: 36.0,
  },
  {
    title: 'Roasted Beet Hummus Wrap',
    description: 'Whole wheat wrap filled with beet hummus, roasted veggies, and greens.',
    ingredients: [
      { name: 'Whole wheat wraps', quantity: 4, unit: 'pieces' },
      { name: 'Cooked beets', quantity: 200, unit: 'g', note: 'diced' },
      { name: 'Chickpeas', quantity: 150, unit: 'g', note: 'canned, drained' },
      { name: 'Tahini', quantity: 40, unit: 'g' },
      { name: 'Lemon juice', quantity: 15, unit: 'ml' },
      { name: 'Garlic', quantity: 2, unit: 'cloves' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Roasted red peppers', quantity: 120, unit: 'g', note: 'sliced' },
      { name: 'Arugula', quantity: 60, unit: 'g' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Blend beets, chickpeas, tahini, lemon juice, garlic, olive oil, salt, and pepper into smooth hummus.',
      'Spread beet hummus over wraps.',
      'Top with roasted peppers and arugula.',
      'Roll wraps tightly and slice in half.',
    ],
    tags: ['lunch', 'vegan', 'healthy'],
    category: 'Main Course',
    servings: 4,
    cookTimeMin: 20,
    kcalPerServing: 280,
    proteinPerServing: 9.5,
    fatPerServing: 12.0,
    carbsPerServing: 34.0,
  },
  {
    title: 'Italian White Bean Soup',
    description: 'Comforting soup with cannellini beans, kale, and tomatoes.',
    ingredients: [
      { name: 'Cannellini beans', quantity: 300, unit: 'g', note: 'canned, drained' },
      { name: 'Kale', quantity: 120, unit: 'g', note: 'chopped' },
      { name: 'Carrot', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Celery', quantity: 2, unit: 'stalks', note: 'diced' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'chopped' },
      { name: 'Garlic', quantity: 3, unit: 'cloves', note: 'minced' },
      { name: 'Diced tomatoes', quantity: 400, unit: 'g' },
      { name: 'Vegetable broth', quantity: 900, unit: 'ml' },
      { name: 'Olive oil', quantity: 20, unit: 'ml' },
      { name: 'Thyme', quantity: 3, unit: 'g' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Heat olive oil in pot and sauté onion, carrot, and celery for 5 minutes.',
      'Add garlic, thyme, and rosemary; cook 1 minute.',
      'Add tomatoes, beans, broth, salt, and pepper; bring to boil.',
      'Reduce heat, add kale, and simmer 20 minutes.',
    ],
    tags: ['soup', 'vegetarian', 'gluten-free', 'healthy'],
    category: 'Soup',
    servings: 4,
    cookTimeMin: 30,
    kcalPerServing: 230,
    proteinPerServing: 10.0,
    fatPerServing: 6.5,
    carbsPerServing: 35.0,
  },
  {
    title: 'Spicy Turkey Chili',
    description: 'Lean turkey chili with kidney beans, corn, and chipotle heat.',
    ingredients: [
      { name: 'Ground turkey', quantity: 500, unit: 'g' },
      { name: 'Kidney beans', quantity: 250, unit: 'g', note: 'canned, rinsed' },
      { name: 'Corn kernels', quantity: 120, unit: 'g' },
      { name: 'Diced tomatoes', quantity: 400, unit: 'g' },
      { name: 'Tomato sauce', quantity: 200, unit: 'ml' },
      { name: 'Onion', quantity: 1, unit: 'piece', note: 'chopped' },
      { name: 'Chipotle in adobo', quantity: 10, unit: 'g', note: 'minced' },
      { name: 'Cumin', quantity: 5, unit: 'g' },
      { name: 'Chili powder', quantity: 6, unit: 'g' },
      { name: 'Olive oil', quantity: 15, unit: 'ml' },
      { name: 'Salt', quantity: 3, unit: 'g' },
      { name: 'Black pepper', quantity: 2, unit: 'g' },
    ],
    steps: [
      'Heat olive oil in pot and cook turkey until browned.',
      'Add onion and chipotle; cook 3 minutes.',
      'Stir in tomatoes, tomato sauce, beans, corn, cumin, chili powder, salt, and pepper.',
      'Simmer 25 minutes, stirring occasionally.',
    ],
    tags: ['dinner', 'high-protein', 'comfort-food', 'spicy'],
    category: 'Main Course',
    servings: 5,
    cookTimeMin: 35,
    kcalPerServing: 360,
    proteinPerServing: 28.0,
    fatPerServing: 12.0,
    carbsPerServing: 35.0,
  },
  {
    title: 'Apple Cinnamon Overnight Oats',
    description: 'Creamy overnight oats with diced apples and warm spices.',
    ingredients: [
      { name: 'Rolled oats', quantity: 160, unit: 'g' },
      { name: 'Milk', quantity: 400, unit: 'ml' },
      { name: 'Greek yogurt', quantity: 120, unit: 'g' },
      { name: 'Apple', quantity: 1, unit: 'piece', note: 'diced' },
      { name: 'Chia seeds', quantity: 20, unit: 'g' },
      { name: 'Cinnamon', quantity: 3, unit: 'g' },
      { name: 'Maple syrup', quantity: 20, unit: 'ml' },
      { name: 'Vanilla extract', quantity: 5, unit: 'ml' },
    ],
    steps: [
      'Combine oats, milk, yogurt, chia seeds, cinnamon, maple syrup, and vanilla in container.',
      'Fold in diced apple, reserving some for topping.',
      'Refrigerate overnight and serve chilled with remaining apple.',
    ],
    tags: ['breakfast', 'vegetarian', 'healthy', 'make-ahead'],
    category: 'Breakfast',
    servings: 4,
    cookTimeMin: 10,
    kcalPerServing: 285,
    proteinPerServing: 12.0,
    fatPerServing: 7.0,
    carbsPerServing: 42.0,
  },
];

async function main() {
  console.log('Starting database seed...');

  // Create default user
  const user = await prisma.user.upsert({
    where: { id: DEFAULT_USER_ID },
    update: {},
    create: {
      id: DEFAULT_USER_ID,
      email: 'user@example.com',
      name: 'Default User',
      locale: 'en',
    },
  });

  console.log('Created user:', user.email);

  // Create recipes
  for (const recipe of recipes) {
    await prisma.recipe.create({
      data: {
        ...recipe,
        ownerId: user.id,
      },
    });
  }

  console.log(`Created ${recipes.length} recipes`);
  console.log('Database seed completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });


